### PR TITLE
Add  NGS Processing slides

### PR DESCRIPTION
**Pull request by jfy133**

### CODE REVIEW

**Comment by MPI-SHH-SummerSchool** [comment]
May I merge this one? (ask by Mei-Shin)

**Comment by jfy133** [comment]
That's up to you. I saw that you would be making all the material available on Monday so I assumed it would make sense to have something?

Unless I misunderstood what the 'material' being released was going to be.

You can merge now but I will probably still be tweaking stuff over the next week or so

(I don't mind either way)

**Comment by MPI-SHH-SummerSchool** [comment]
The material will be some datasets that students need to download before the class, and the poster template (if the student is going to make a poster) 
I think it's also good to have some slides release before the course.  But if you are still working on it, we can merge it later?

**Comment by jfy133** [comment]
Ah understood! Then yes, I'll close this for now and once it's mostly finished then I'll open again to merge

**Comment by jfy133** [comment]
@MPI-SHH-SummerSchool content is basically there. Will maybe have a couple more PRs over the next week or so, but these would be minor tweaks.

**Review by MPI-SHH-SummerSchool — APPROVED** [review]

**Pull request merged**
